export let screenNames = {
  BottomTabNavigation: 'BottomTabNavigation',
  splash: 'Splash',
  login: 'Login',
  verifyOTP: 'VerifyOTP',
  register: 'Register',
  home: 'Home',
  drawerNavigation: 'Drawer Navigation',
  quotes: 'Quotes',
  dailyDarshan: 'Daily Darshan',
  updates: 'FOLK Updates',
  folkVideos: 'FOLK Videos',
  yfhForm: 'YFH',
  events: 'Events',
  mainScreen: 'MainScreen',
  switcherScreen: 'SwitcherScreen',
};
